### ISSUE TITLE
1.9.x update is very glitchy

### ISSUE THREAD

**Issue by kkeijzer** [flathub/org.telegram.desktop#133]
I have pretty servere rendering issues on Ubuntu 18.04.3 running the latest Telegram Desktop flatpak.
It also no longer uses native decorations.

I can't really find anything helpful in the logs. Here is a video of what happens: https://quietlife.nl/telegram-flatpak-glitch.webm

Rolling back to 1.8.15 solves all issues.

**Comment by SnejUgal** [comment]
I'm on Ubuntu 18.04, too, running Wayland, and experienced the same issue. I fixed it by setting `QT_QPA_PLATFORM=xcb` for Telegram. Maybe it was too early to remove the workaround to always run Telegram on X11?

**Comment by kkeijzer** [comment]
Thanks, that indeed fixes the problem. The only remaining issue is that, when minimized to systray, clicking the Telegram icon in the dock or in the app drawer does not bring the window back to foreground, but launches a new instance with another tray icon. This was not the case in 1.8.x.

**Comment by grulja** [comment]
Can you try https://github.com/flathub/org.telegram.desktop/pull/134 once it finishes test build, whether it works as expected?

**Comment by ilya-fedin** [comment]
@kkeijzer @SnejUgal which hardware do you have?

**Comment by SnejUgal** [comment]
@ilya-fedin this problem here doesn't seem to be hardware but some incompatibility with Ubuntu 18.04. I just tested how Telegram runs under Wayland on my old laptop with both Ubuntu 18.04 (with GNOME 3.28) and Manjaro GNOME (with GNOME 3.36) installed (this laptop runs Intel Core i5 M480 and integrated graphics FWIW). In Ubuntu, Telegram glitched as soon as I pressed the log in button and then pressed back; in Manjaro I didn't notice any glitches, but decorations still don't show the close button.

As far as I remember, the problem started after some KDE platform update and affect other apps too. For example, OpenSCAD also has odd decorations and glitches, but in this case glitches are rare and don't hurt usability much.

**Comment by ilya-fedin** [comment]
> also has odd decorations

these decorations are because gnome doesn't support xdg-decoration protocol and Qt renders a stub. Gnomers says that they won't implement this protocol, so the situation won't change most likely.

> and glitches

Maybe https://gitlab.gnome.org/GNOME/mutter/issues/199?

But, I think, XWayland should be forced for everybody just because old gnome version has a bad behavior, I think QT_QPA_PLATFORM override should be removed and anyone who experience any issues can add it for themselves.

**Comment by kkeijzer** [comment]
> @kkeijzer which hardware do you have?

Lenovo X200 with coreboot 4.10; Intel GMA X4500 GPU.
