### ISSUE TITLE
Copy and Paste Under Wayland

### ISSUE THREAD

**Issue by carwyn** [flathub/org.telegram.desktop#236]
Seems like pasting text into Telegram Flatpak under Wayland is broken.

**Comment by ilya-fedin** [comment]
It works for me

**Comment by carwyn** [comment]
Hmm, I'll investigate further and re-open if needed. This could be something my end as Telegram isn't the only thing playing up. Apologies.

**Comment by NotAFile** [comment]
It does not work for me. Text works, but images and media are broken.

**Comment by ilya-fedin** [comment]
I dunno, tdesktop just uses Qt API. Probably Qt has some bug with clipboard then. :man_shrugging:

**Comment by ilya-fedin** [comment]
I tried to copy an image from firefox with `MOZ_ENABLE_WAYLAND=1` to Telegram on Weston and can say that it works just fine

**Comment by NotAFile** [comment]
> tdesktop just uses Qt API

It also heavily patches Qt which regularly causes all kinds of problems that don't occur in other programs.

> I tried to copy an image from firefox with MOZ_ENABLE_WAYLAND=1 to Telegram on Weston and can say that it works just fine
This works fine for me too. The issue is when copying an image from telegram to another application.

**Comment by ilya-fedin** [comment]
> It also heavily patches Qt which regularly causes all kinds of problems that don't occur in other programs.

Well, from what I've seen, these patches are backports from future Qt versions and they fixes problems rather create. There are also some custom patches that fixes some things on Windows and macOS (and I wrote a patch to provide window shadows on Wayland). Unfortunately, these patches can't be used in flatpak since bundling Qt is prohibited and KDE runtime must be used, so this couldn't be a problem.

> The issue is when copying an image from telegram to another application.

Oh, I've seen such a bugreport, but this should be fixed in 5.15.2 according to https://bugreports.qt.io/browse/QTBUG-88293

**Comment by ilya-fedin** [comment]
Looks like KDE runtime already uses 5.15.2, so looks like the bug is not fixed even though is marked as fixed

**Comment by ilya-fedin** [comment]
I'm trying to find a non-Qt Wayland application where I can paste an image from tdesktop in order to reproduce this, but can't find one. How to reproduce this?

**Comment by ilya-fedin** [comment]
I tried to copy from Telegram and paste to a Qt application (tested with nomacs) on Weston and it works just fine for me.
