### ISSUE TITLE
Aliased fonts and wrong pointer icon on GNOME Wayland

### ISSUE THREAD

**Issue by why-not-try-calmer** [flathub/org.telegram.desktop#363]
Here's a screenshot to see what I mean:
![ugly_fonts_wrong_pointer](https://user-images.githubusercontent.com/19554213/147852178-bdab5dc0-32d4-40b8-86b6-a2836401c561.png)

Using GNOME 40.4.0.

**Comment by ilya-fedin** [comment]
Only packaging issues are accepted here

**Comment by why-not-try-calmer** [comment]
How do you know it's not a packaging issue?

**Comment by ilya-fedin** [comment]
What you see is Qt started defaulting to Wayland. GNOEM on Wayland sets cursor theme and font rendering settings with gtk-specific settings rather than with standardized fontconfig and non-gtk XCURSOR_THEME/XCURSOR_SIZE variables (the latter is not a standard, but used by something else: Qt, SDL, mpv).

**Comment by why-not-try-calmer** [comment]
Oh, interesting, that's a good news that Qt started defaulting to Wayland. In fact I had surmised something like this because after overriding `flatpak run` with `--env QT_QPA_PLATFORM =xcb` all my issues vanished. Which solution would you recommend in order to take advantage of the new defaults on GNOME Wayland?

**Comment by gasinvein** [comment]
FWIW I don't have this issue on GNOME 41. The cursor in Telegram is bigger than it should be, but its icon is normal.

**Comment by ilya-fedin** [comment]
You can set XCURSOR_THEME/XCURSOR_SIZE variables for the cursor or ask GNOEM developers to set them automatically according to GUI settings. For fonts... Well, that's complicated. Even if you configure fontconfig, that won't affect flatpak applications since flatpak doesn't mount host fontconfig since fontconfig breaks config format in every release (#1563). In other words, there's no solution for font settings in flatpak, I can only suggest to install tdesktop from static binary or from distro repos and then configure fontconfig.

**Comment by ilya-fedin** [comment]
> FWIW I don't have this issue on GNOME 41. The cursor in Telegram is bigger than it should be, but its icon is normal.

Icon? You mean that 'pointer icon'? I guess he wanted to say 'cursor bitmap'.

**Comment by ilya-fedin** [comment]
Ah, you mean Telegram uses your cursor theme out-of-the-box? Well, it depends on what /usr/share/icons/default is linked to on your system, Qt uses it by default. If you change your cursor theme to something non-standard, you will see this problem as well.
