### ISSUE TITLE
Failed to gtk_init_check(0, 0)!

### ISSUE THREAD

**Issue by eternal-sorrow** [flathub/org.telegram.desktop#72]
Discussion of this issue started at #55, but after I did some debugging, I figured this has nothing to do with notification system, as it is more general problem.

I enabled the debug logs and was able to find out that telegram fails to initialise GTK integration. The error line is:
```
Failed to gtk_init_check(0, 0)!
```

Running the app with `GTK_DEBUG=all` I got this:
```
Gtk-Message: 03:41:29.191: Failed to open display (null)
Gtk-Message: 03:41:29.191: Failed to separate connection to default display
```

My wild guess is that as I run telegram on wayland (sway compositor) and it runs natively (does not use Xwayland compatibility layer), but when initialising GTK, it forces using x11 backend. I don't know if it could cause issues.

**Comment by jurf** [comment]
I can reproduce this with `flatpak run --nosocket=x11 --env=QT_QPA_PLATFORM=wayland org.telegram.desktop`.

**Comment by grulja** [comment]
This is most probably because we build Telegram with Gtk disabled, only libnotify is patched to be available for tray support. Unfortunately it seems that Ayatana-appindicator depends on that and support for it is not build. Gtk is disabled to avoid using Gtk file dialogs and to force telegram use native dialogs which means using portals. I guess with some modifications this support can be restored, but I don't have currently time for that and I don't want to revert my change disabling Gtk to make it work and let Telegram again to use Gtk file dialogs.

**Comment by grulja** [comment]
Should be fixed with https://github.com/flathub/org.telegram.desktop/pull/74.

**Comment by eternal-sorrow** [comment]
Still does not work. I guess it wasn't related.

**Comment by grulja** [comment]
Right, this will most likely need Ayatana as a dependency present during the build. But the gtk_init_check() failure is gone, or still present?

**Comment by grulja** [comment]
Hmm, but we actually have appindicator3 there enabled so it should work in my opinion.

**Comment by eternal-sorrow** [comment]
> But the gtk_init_check() failure is gone, or still present?
still present, nothing changed

**Comment by grulja** [comment]
Oh, I see now what is the problem, I first thought the problem is somewhere else. I should have read your report properly. It's pretty obvious why it's happening, Telegram only allows x11 backend.

The problematic part is here: https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/platform/linux/linux_libs.cpp#L104

@john-preston do you think we can do something about it?

**Comment by eternal-sorrow** [comment]
Any news here?

**Comment by eternal-sorrow** [comment]
Okay, now this should be fixed upsteram.

**Comment by eternal-sorrow** [comment]
All right, this is fixed now.
